### PR TITLE
Recognize modification notes from authoritative source

### LINKED ISSUE #16: Recognize modification notes from authoritative source relationship field
Example rendered item missing source relationship modification note: https://glossary.metaverse-standards.org/concepts/110/

Same item’s source containing “modified” relationship and modification note: https://github.com/MetaverseStandards/metaversestandards-glossary/blob/14600de6147180834ef0d5fc6c7fdc5ca4969d46/msfglossary/localized-concept/f2c8bcd6-f1ab-433f-97a6-187ca3a0fb5a.yaml#L20-L22

We would want to display relationship & optional modification note in a way that is similar to how it looks here: https://isotc211.geolexica.org/concepts/10/ (see source field).

### PR DESCRIPTION
**Pull request by HassanAkbar**
Recognize modification notes from authoritative source relationship field

closes #16

### CODE REVIEW

**Comment by HassanAkbar** [comment]
@strogonoff One thing that I noticed is that the spelling of `modification` key is wrong in the [yaml file](https://github.com/MetaverseStandards/metaversestandards-glossary/blob/14600de6147180834ef0d5fc6c7fdc5ca4969d46/msfglossary/localized-concept/f2c8bcd6-f1ab-433f-97a6-187ca3a0fb5a.yaml#L20-L22).

**Comment by strogonoff** [comment]
I am not familiar enough with this project to properly understand the changes. Any potential problems if we merge this?

**Comment by strogonoff** [comment]
> @strogonoff One thing that I noticed is that the spelling of `modification` key is wrong in the [yaml file](https://github.com/MetaverseStandards/metaversestandards-glossary/blob/14600de6147180834ef0d5fc6c7fdc5ca4969d46/msfglossary/localized-concept/f2c8bcd6-f1ab-433f-97a6-187ca3a0fb5a.yaml#L20-L22).

This I believe has been fixed since.

**Comment by HassanAkbar** [comment]
@strogonoff Verified, this has been fixed.

**Review by ronaldtse — APPROVED** [review]
Thank you @HassanAkbar ! Can you please help merge and release? Thanks.

**Review by strogonoff — APPROVED** [review]

**Comment by HassanAkbar** [comment]
@ronaldtse released version `1.8.14`.

**Pull request merged**
